// Indicatifs téléphoniques mondiaux (extrait représentatif, ~70 pays).
// Chaque entrée: { name, iso2, dial, flag }
export type Country = { name: string; iso2: string; dial: string; flag: string };

export const COUNTRIES: Country[] = [
  { name: 'France', iso2: 'FR', dial: '+33', flag: '🇫🇷' },
  { name: 'Bénin', iso2: 'BJ', dial: '+229', flag: '🇧🇯' },
  { name: 'Côte d’Ivoire', iso2: 'CI', dial: '+225', flag: '🇨🇮' },
  { name: 'Sénégal', iso2: 'SN', dial: '+221', flag: '🇸🇳' },
  { name: 'Mali', iso2: 'ML', dial: '+223', flag: '🇲🇱' },
  { name: 'Burkina Faso', iso2: 'BF', dial: '+226', flag: '🇧🇫' },
  { name: 'Togo', iso2: 'TG', dial: '+228', flag: '🇹🇬' },
  { name: 'Niger', iso2: 'NE', dial: '+227', flag: '🇳🇪' },
  { name: 'Nigeria', iso2: 'NG', dial: '+234', flag: '🇳🇬' },
  { name: 'Ghana', iso2: 'GH', dial: '+233', flag: '🇬🇭' },
  { name: 'Cameroun', iso2: 'CM', dial: '+237', flag: '🇨🇲' },
  { name: 'Gabon', iso2: 'GA', dial: '+241', flag: '🇬🇦' },
  { name: 'Congo', iso2: 'CG', dial: '+242', flag: '🇨🇬' },
  { name: 'RD Congo', iso2: 'CD', dial: '+243', flag: '🇨🇩' },
  { name: 'Maroc', iso2: 'MA', dial: '+212', flag: '🇲🇦' },
  { name: 'Algérie', iso2: 'DZ', dial: '+213', flag: '🇩🇿' },
  { name: 'Tunisie', iso2: 'TN', dial: '+216', flag: '🇹🇳' },
  { name: 'Égypte', iso2: 'EG', dial: '+20', flag: '🇪🇬' },
  { name: 'Afrique du Sud', iso2: 'ZA', dial: '+27', flag: '🇿🇦' },
  { name: 'Kenya', iso2: 'KE', dial: '+254', flag: '🇰🇪' },
  { name: 'Éthiopie', iso2: 'ET', dial: '+251', flag: '🇪🇹' },
  { name: 'Tanzanie', iso2: 'TZ', dial: '+255', flag: '🇹🇿' },
  { name: 'Rwanda', iso2: 'RW', dial: '+250', flag: '🇷🇼' },
  { name: 'Belgique', iso2: 'BE', dial: '+32', flag: '🇧🇪' },
  { name: 'Suisse', iso2: 'CH', dial: '+41', flag: '🇨🇭' },
  { name: 'Luxembourg', iso2: 'LU', dial: '+352', flag: '🇱🇺' },
  { name: 'Royaume-Uni', iso2: 'GB', dial: '+44', flag: '🇬🇧' },
  { name: 'Irlande', iso2: 'IE', dial: '+353', flag: '🇮🇪' },
  { name: 'Allemagne', iso2: 'DE', dial: '+49', flag: '🇩🇪' },
  { name: 'Espagne', iso2: 'ES', dial: '+34', flag: '🇪🇸' },
  { name: 'Italie', iso2: 'IT', dial: '+39', flag: '🇮🇹' },
  { name: 'Portugal', iso2: 'PT', dial: '+351', flag: '🇵🇹' },
  { name: 'Pays-Bas', iso2: 'NL', dial: '+31', flag: '🇳🇱' },
  { name: 'Suède', iso2: 'SE', dial: '+46', flag: '🇸🇪' },
  { name: 'Norvège', iso2: 'NO', dial: '+47', flag: '🇳🇴' },
  { name: 'Danemark', iso2: 'DK', dial: '+45', flag: '🇩🇰' },
  { name: 'Finlande', iso2: 'FI', dial: '+358', flag: '🇫🇮' },
  { name: 'Pologne', iso2: 'PL', dial: '+48', flag: '🇵🇱' },
  { name: 'Grèce', iso2: 'GR', dial: '+30', flag: '🇬🇷' },
  { name: 'Turquie', iso2: 'TR', dial: '+90', flag: '🇹🇷' },
  { name: 'Russie', iso2: 'RU', dial: '+7', flag: '🇷🇺' },
  { name: 'Ukraine', iso2: 'UA', dial: '+380', flag: '🇺🇦' },
  { name: 'États-Unis', iso2: 'US', dial: '+1', flag: '🇺🇸' },
  { name: 'Canada', iso2: 'CA', dial: '+1', flag: '🇨🇦' },
  { name: 'Mexique', iso2: 'MX', dial: '+52', flag: '🇲🇽' },
  { name: 'Brésil', iso2: 'BR', dial: '+55', flag: '🇧🇷' },
  { name: 'Argentine', iso2: 'AR', dial: '+54', flag: '🇦🇷' },
  { name: 'Chili', iso2: 'CL', dial: '+56', flag: '🇨🇱' },
  { name: 'Colombie', iso2: 'CO', dial: '+57', flag: '🇨🇴' },
  { name: 'Pérou', iso2: 'PE', dial: '+51', flag: '🇵🇪' },
  { name: 'Chine', iso2: 'CN', dial: '+86', flag: '🇨🇳' },
  { name: 'Japon', iso2: 'JP', dial: '+81', flag: '🇯🇵' },
  { name: 'Corée du Sud', iso2: 'KR', dial: '+82', flag: '🇰🇷' },
  { name: 'Inde', iso2: 'IN', dial: '+91', flag: '🇮🇳' },
  { name: 'Pakistan', iso2: 'PK', dial: '+92', flag: '🇵🇰' },
  { name: 'Bangladesh', iso2: 'BD', dial: '+880', flag: '🇧🇩' },
  { name: 'Indonésie', iso2: 'ID', dial: '+62', flag: '🇮🇩' },
  { name: 'Vietnam', iso2: 'VN', dial: '+84', flag: '🇻🇳' },
  { name: 'Thaïlande', iso2: 'TH', dial: '+66', flag: '🇹🇭' },
  { name: 'Philippines', iso2: 'PH', dial: '+63', flag: '🇵🇭' },
  { name: 'Malaisie', iso2: 'MY', dial: '+60', flag: '🇲🇾' },
  { name: 'Singapour', iso2: 'SG', dial: '+65', flag: '🇸🇬' },
  { name: 'Émirats A. U.', iso2: 'AE', dial: '+971', flag: '🇦🇪' },
  { name: 'Arabie saoudite', iso2: 'SA', dial: '+966', flag: '🇸🇦' },
  { name: 'Qatar', iso2: 'QA', dial: '+974', flag: '🇶🇦' },
  { name: 'Israël', iso2: 'IL', dial: '+972', flag: '🇮🇱' },
  { name: 'Liban', iso2: 'LB', dial: '+961', flag: '🇱🇧' },
  { name: 'Australie', iso2: 'AU', dial: '+61', flag: '🇦🇺' },
  { name: 'Nouvelle-Zélande', iso2: 'NZ', dial: '+64', flag: '🇳🇿' },
];
