export const PODCAST_COVERS = {
  c1: 'https://images.unsplash.com/photo-1773858440557-cdb7fa2275bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
  c2: 'https://images.unsplash.com/photo-1764662028086-e74ce491080e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
  c3: 'https://images.unsplash.com/photo-1609128716654-54cdde6911ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
  c4: 'https://images.unsplash.com/photo-1709513641614-f1b8fd550761?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
  c5: 'https://images.unsplash.com/photo-1666886573553-453e9cdbd967?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
  c6: 'https://images.unsplash.com/photo-1770283553838-769c5f97d55c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=85&w=900',
};

export const PODCAST_SAMPLE = 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_4d54a40fcb.mp3?filename=relaxing-145038.mp3';

export type PodcastLang = 'fr' | 'fon' | 'yor' | 'wol' | 'hau' | 'ibo' | 'lin' | 'bam' | 'ful' | 'dyu' | 'sen' | 'zar';
export type PodcastEpisode = {
  id: string; title: string; cat: string; tag: string; cover: string;
  host: string; duration: string; durationSec: number; desc: string; src: string; transcript?: string;
  lang: PodcastLang; publishedAt: number;
};

export const PODCAST_EPISODES: PodcastEpisode[] = [
  { id: 'e1', title: "Bien manger avec un petit budget : guide pratique au marché", cat: 'nutrition', tag: 'bg-emerald-500', cover: PODCAST_COVERS.c1, host: 'Dr. Aïssata Bah', duration: '32 min', durationSec: 1920, src: PODCAST_SAMPLE, lang: 'fr', publishedAt: 1746489600000,
    desc: "Comment composer des repas équilibrés sans exploser son budget ? Notre nutritionniste guide pas à pas le choix des produits, la planification des courses et la cuisson qui préserve les nutriments, avec des recettes faciles testées en direct.",
    transcript: "Bonjour à tous, bienvenue dans cet épisode du podcast HEALTHY PAGE. Aujourd'hui nous parlons d'un sujet qui touche chaque foyer : bien manger avec un petit budget. Trop souvent on associe alimentation équilibrée et dépenses élevées. Pourtant en choisissant les produits locaux de saison, en privilégiant les légumineuses comme le niébé, le haricot ou les arachides, et en limitant les produits ultra-transformés, on peut composer des assiettes complètes pour toute la famille. Premier conseil : planifier la semaine avant d'aller au marché — trois recettes phares, une liste de courses, un budget fixe. Deuxième conseil : cuisiner en grande quantité une fois et réutiliser intelligemment les bases pendant deux à trois jours. Troisième conseil : remplacer un repas de viande par semaine par un plat de légumineuses, économique et riche en protéines." },
  { id: 'e2', title: "Apprendre à respirer pour calmer une crise d'anxiété", cat: 'mental', tag: 'bg-indigo-500', cover: PODCAST_COVERS.c2, host: 'Mme Fatou Diop', duration: '24 min', durationSec: 1440, src: PODCAST_SAMPLE, lang: 'fr', publishedAt: 1746316800000,
    desc: "Trois techniques simples, concrètes et discrètes, à pratiquer partout, pour reprendre la maîtrise du souffle quand le cœur s'emballe et que les pensées tournent en boucle.",
    transcript: "Bonjour, je suis Fatou Diop psychologue. Quand l'anxiété monte, le souffle devient court, le cœur s'accélère et la pensée s'emballe. La bonne nouvelle : la respiration est une porte d'entrée immédiate pour calmer le système nerveux. Première technique, le carré : inspirez quatre secondes, retenez quatre, expirez quatre, retenez quatre, recommencez cinq fois. Deuxième technique, la cohérence cardiaque : six respirations lentes par minute pendant cinq minutes, trois fois par jour. Troisième technique, le souffle de l'abeille : bouche fermée, faites vibrer un son grave en expirant. Pratiquez ces gestes au calme avant d'en avoir besoin pour qu'ils deviennent réflexes." },
  { id: 'e3', title: "Premiers mois de bébé : reconnaître les vrais signes d'alerte", cat: 'maternite', tag: 'bg-pink-500', cover: PODCAST_COVERS.c4, host: 'Dre Mariam Touré', duration: '41 min', durationSec: 2460, src: PODCAST_SAMPLE, lang: 'fon', publishedAt: 1746057600000,
    desc: "Fièvre, pleurs prolongés, refus de téter, signes de déshydratation : la pédiatre distingue ce qui peut attendre, ce qui demande un avis médical et ce qui impose les urgences.",
    transcript: "Les premiers mois sont riches en émotions et en doutes. Certaines situations sont bénignes, d'autres demandent une consultation rapide. Une fièvre supérieure à trente-huit degrés avant trois mois impose les urgences sans délai. Un refus total de téter pendant plus de six heures, des pleurs inconsolables sur plusieurs heures, des selles sanglantes, une fontanelle creuse ou bombée sont aussi des signaux d'alerte. À l'inverse, un hoquet fréquent, quelques régurgitations après la tétée ou un sommeil agité peuvent rester normaux. Faites confiance à votre instinct : si quelque chose vous inquiète, appelez votre pédiatre." },
  { id: 'e4', title: "Hypertension : la maladie silencieuse qui touche un adulte sur trois", cat: 'prevention', tag: 'bg-sky-500', cover: PODCAST_COVERS.c5, host: 'Dr. Kwame Asante', duration: '28 min', durationSec: 1680, src: PODCAST_SAMPLE, lang: 'fr', publishedAt: 1745798400000,
    desc: "Pourquoi mesurer sa tension change une vie. Le cardiologue explique les facteurs de risque, l'importance du dépistage régulier et des habitudes simples qui font baisser durablement la pression artérielle.",
    transcript: "L'hypertension est silencieuse mais dévastatrice. Elle abîme cœur, reins, cerveau pendant des années sans symptôme. Le dépistage est simple : une mesure tous les six mois après quarante ans, ou plus tôt en cas d'antécédents familiaux. La cible reste inférieure à cent quarante sur quatre-vingt-dix. Pour la faire baisser, trois leviers majeurs : réduire le sel ajouté, marcher trente minutes par jour, gérer le stress. Le traitement médicamenteux complète mais ne remplace pas l'hygiène de vie. Apportez votre carnet de tension à chaque consultation pour ajuster avec précision." },
  { id: 'e5', title: "15 minutes par jour : une routine pour le dos, à la maison", cat: 'sport', tag: 'bg-orange-500', cover: PODCAST_COVERS.c3, host: 'Coach Yannick Mensah', duration: '19 min', durationSec: 1140, src: PODCAST_SAMPLE, lang: 'wol', publishedAt: 1745452800000,
    desc: "Une séance courte et progressive, sans matériel, pour soulager les tensions du dos liées à la position assise prolongée et renforcer la sangle abdominale en douceur.",
    transcript: "Le dos souffre quand on reste assis trop longtemps. Quinze minutes par jour suffisent pour inverser la tendance. On commence par cinq minutes de mobilité : roulements d'épaules, bascules du bassin, étirement du chat. Ensuite cinq minutes de gainage doux : planche sur les genoux, pont fessier, superman. On termine par cinq minutes d'étirements profonds : pigeon, posture de l'enfant, torsion allongée. Respirez lentement à chaque mouvement. La régularité prime sur l'intensité : mieux vaut quinze minutes par jour qu'une heure le dimanche." },
  { id: 'e6', title: "Le moringa : superaliment ou simple effet de mode ?", cat: 'tradition', tag: 'bg-lime-500', cover: PODCAST_COVERS.c6, host: 'Pr. Adjoa Mensah', duration: '36 min', durationSec: 2160, src: PODCAST_SAMPLE, lang: 'yor', publishedAt: 1744934400000,
    desc: "La pharmacologue passe au crible les vertus du moringa, son juste usage, ses interactions à connaître et la place qu'il peut occuper dans une alimentation équilibrée au quotidien.",
    transcript: "Le moringa oleifera est riche en protéines, en fer, en calcium et en vitamines A et C. Les feuilles séchées concentrent les nutriments. Il complète utilement une alimentation pauvre en végétaux variés. Cependant, il n'est pas un médicament miracle. Une cuillère à café de poudre par jour suffit : au-delà, l'excès de fibres peut perturber la digestion. Attention aux interactions avec les anticoagulants et certains traitements de la thyroïde. La meilleure stratégie reste la diversité : moringa, légumes verts locaux, légumineuses, fruits de saison, dans une assiette équilibrée." },
];
